### ISSUE TITLE
LCM behind Nginx

### ISSUE THREAD

**Issue by sudhakar890** [arminc/k8s-platform-lcm#87]
I am running lcm tool behind Nginx and the url used to access `http://example.com/lcm`. The web ui is not loading properly because it is unable to find the styles.css file. Is there any configuration I have to set to load correctly?

**Comment by arminc** [comment]
The problem I think is that the template right now has a hardcoded line "/static/styles.css" which would therefore go to "http://example.com/static/styles.css" instead of "http://example.com/lcm/static/styles.css"
